### PR TITLE
chore: reuse github workflows

### PR DESCRIPTION
**Pull request by kenjis**
See https://github.com/codeigniter4/CodeIgniter4/issues/7819

The following is not updated:
- phpunit.yml
- rector.yml

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Review by MGatner — APPROVED** [review]

**Comment by MGatner** [comment]
Why not rector.yml? Some dependency issues as Settings?

**Comment by kenjis** [comment]
Rector is not required in this repository.

**Comment by MGatner** [comment]
We should probably change that to use our standard. The YAML is installing Rector globally but the version is way behind: ^0.15.1

Doesn't have to be part of this PR but I would like to see this consistent with our other repos.

**Comment by kenjis** [comment]
Let's update it after the new devkit release.

**Pull request merged**
