### PR TITLE
Dark mode fixes

### PR DESCRIPTION
**Pull request by lonnieezell**
- Responsive top menu needs black background
- Responsive top menu active link needed spacing fixed
- Responsive top menu should hide borders and use font weight instead

### CODE REVIEW

**Comment by kenjis** [comment]
Why do you remove News?

**Review by Arhell — APPROVED** [review]

**Review by kenjis — CHANGES_REQUESTED** [review]
Removing News has nothing to do with this PR.

**Comment by lonnieezell** [comment]
It wasn't really intended to be. I accidentally branched off of the other PR. This can wait until we decide about the other one. I'd like them both to go live together if they're both approved.

**Comment by kenjis** [comment]
I sent a new PR #395

**Comment by kenjis** [comment]
Closed by #395

**Pull request closed without merging**
