### PR TITLE
Update ci-responsive.css

### PR DESCRIPTION
**Pull request by demyr17**
Changes due to the new dark-theme that were skipped last time

### CODE REVIEW

**Comment by kenjis** [comment]
Why don't you send one PR for the dark theme?

**Comment by demyr17** [comment]
Still trying to learn how to use Github effectively @kenjis . I'm not a developer originally. I build websites and I have built so many of them until today but even the most corporate ones don't require you to use Github. Except for our CodeIgniter project I only use it to follow some scripts&developers. But it looks like I cannot use it. Sorry for the inconvenience.

**Comment by kenjis** [comment]
@demyr17 You don't know git at all?
All you need to do is to commit (save) all the modified files in a branch for the PR.

GitHub provides Web IDE.
Navigate to https://github.com/codeigniter4projects/website/tree/demyr17-patch-4
and press `.` key. You can use it, and can modify files in the `demyr17-patch-4` branch.

If you want to try to create a PR for easy reviewing, I will support you.

**Comment by demyr17** [comment]
> All you need to do is to commit (save) all the modified files in a branch for the PR.

OK, I got the point. Huge thanks. I hope to succeed it next time.

BTW, when I download the project it doesn't work on my local. If I could see the result (real pages) like you all do, the process would be smoother. How can I see the pages after my commit(s)?

**Comment by kenjis** [comment]
You can run the site on your local.
See https://github.com/codeigniter4projects/website#installation

**Review by Arhell — APPROVED** [review]

**Comment by demyr17** [comment]
> You can run the site on your local. See https://github.com/codeigniter4projects/website#installation

Oh, thank you. However I get **_Class "Github\Client" not found_** error saying **_APPPATH\Config\Services.php at line 40_** and I can't find a proper help on internet that works.

**Comment by kenjis** [comment]
Did you run `composer install`?

**Comment by demyr17** [comment]
Yes, and a few minutes ago I made another-clean install in a new directory from the scratch. But now I have **You must set an access token before using the GitHub service** error  which points **APPPATH\Config\Services.php at line 47**

**Comment by kenjis** [comment]
You need to set your GITHUB_ACCESS_TOKEN in `.env`
```
GITHUB_ACCESS_TOKEN = ghp_xxxxx
```

**Comment by demyr17** [comment]
It gave an SQLite error but I fixed it in php.ini file. However, then it gave this error for which I couldn't find a solution on web
**SQLite3::query(): Unable to prepare statement: 1, no such table: fx_threads** -  **SYSTEMPATH\Database\SQLite3\Connection.php at line 146**

**Comment by kenjis** [comment]
Did you run `php spark migrate -all`?
https://github.com/codeigniter4projects/website#installation

**Comment by demyr17** [comment]
> Did you run `php spark migrate -all`? https://github.com/codeigniter4projects/website#installation

Yess. That fixed it. Now I can fix all the missing points easily. Huge thanks @kenjis

**Comment by lonnieezell** [comment]
There's also a setting in the .env, `MOCK_MYBB ` that can be set to true to return some simple fake data for the database threads portion.

**Pull request closed without merging**
