### PR TITLE
chore: delete github/workflows/unused.yml for now

### PR DESCRIPTION
**Pull request by kenjis**
Delete unused.yml untile it has settled.

See https://github.com/codeigniter4projects/website/pull/258#issuecomment-1074943494

---

See https://github.com/codeigniter4projects/website/runs/5390659728?check_suite_focus=true

>   [Symfony\Component\Console\Exception\RuntimeException]  
  The "--profile" option does not exist.

### CODE REVIEW

**Comment by kenjis** [comment]
@MGatner I don't know how composer-unused works.
But I ran it locally, and also got Unused packages.
How to fix?

```
$ php composer-unused.phar --excludePackage=php --excludePackage=guzzlehttp/guzzle --excludePackage=http-interop/http-factory-guzzle

Results
-------

Found 1 used, 4 unused, 2 ignored and 1 zombie packages

 Used packages
 ✓ php (required by: codeigniter4/cache)

 Unused packages
 ✗ codeigniter4/cache
 ✗ codeigniter4/codeigniter4
 ✗ knplabs/github-api
 ✗ league/commonmark

 Ignored packages
 ○ guzzlehttp/guzzle (ignored by NamedFilter(userProvided: true, string: guzzlehttp/guzzle))
 ○ http-interop/http-factory-guzzle (ignored by NamedFilter(userProvided: true, string: http-interop/http-factory-guzzle))

 Zombies exclusions (did not match any package)
 💀 NamedFilter(userProvided: true, string: php)
```

**Comment by MGatner** [comment]
It's gone through some major changes, including some feature requests of mine. You could try using the Config template from DevKit and see if that resolves some of these. For now though it might be easier to pull the Action YAML until this tool has settled.

**Comment by kenjis** [comment]
> You could try using the Config template from DevKit and see if that resolves some of these. 

I tried, but it does not work.

> For now though it might be easier to pull the Action YAML until this tool has settled.

What do you mean? What is the Action YAML?

**Comment by kenjis** [comment]
I got:
to pull the action yaml = to remove the action yaml.

I did so.

**Review by MGatner — APPROVED** [review]

**Pull request merged**
