### PR TITLE
Missing Fixes for the Dark Theme

### PR DESCRIPTION
**Pull request by demyr17**
I finally managed to see the results on my local with the great help of @kenjis and I think everything is set now.

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Review by lonnieezell — APPROVED** [review]

**Comment by lonnieezell** [comment]
Thanks @demyr17 ! 

Does this PR need the other PRs still or can they be closed?

**Comment by kenjis** [comment]
@demyr17 If this PR does not have all necessary changes for the dark theme, 
add missing files in this PR and close the other PRs.

**Comment by demyr17** [comment]
> @demyr17 If this PR does not have all necessary changes for the dark theme, add missing files in this PR and close the other PRs.

Could you please help me again by pointing out what do you mean by other PRs? (Soorry).

**Comment by kenjis** [comment]
No problem.
#380 and #381

**Comment by demyr17** [comment]
Huge thanks again. How lucky I am to have such helpful people around me.
Done. They're closed.

**Comment by kenjis** [comment]
- [ ] News - the page is turning white and switching again to the dark mode makes a difference only for the navigation bar.
- [ ] Contribute - some texts are black, so we cannot read them
- [ ] Security Disclosures - same issue as above
- [ ] Policies - same issue as above

**Comment by kenjis** [comment]
@demyr17 Some texts are black, so we cannot read them.
Screenshot 2023-06-22 8 29 10
Screenshot 2023-06-22 8 29 24

**Review by kenjis — APPROVED** [review]
LGTM!

**Comment by lonnieezell** [comment]
@demyr17 Thanks so much for getting through this even though they were unfamiliar waters for you!

**Comment by demyr17** [comment]
> @demyr17 Thanks so much for getting through this even though they were unfamiliar waters for you!

You're welcome. I thank you a lot for your patience and guidance.

**Pull request merged**
