### PR TITLE
fix: v4 zip download link

### LINKED ISSUE #203: CI4 Download button should link to codeigniter4/framework
Now it links to https://api.github.com/repos/codeigniter4/CodeIgniter4/zipball/v4.1.7
`codeigniter4/CodeIgniter4` is the development repository.

See https://www.codeigniter.com/download

### PR DESCRIPTION
**Pull request by kenjis**
Fixes #203

See https://www.codeigniter.com/download
The Download button's link is https://api.github.com/repos/codeigniter4/CodeIgniter4/zipball/v4.2.3

### CODE REVIEW

**Comment by kenjis** [comment]
```console
Run vendor/bin/php-cs-fixer fix --verbose --ansi --dry-run --using-cache=no --diff
  vendor/bin/php-cs-fixer fix --verbose --ansi --dry-run --using-cache=no --diff
  shell: /usr/bin/bash -e {0}
  env:
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: 1
    COMPOSER_AUTH: {"github-oauth": {"github.com": "***"}}
PHP CS Fixer 3.9.3 Grand Awaiting by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 7.4.30
Loaded config CodeIgniter4 Coding Standards from "/home/runner/work/website/website/.php-cs-fixer.dist.php".
.....................F.........................................  63 / 102 ( 62%)
.......................................                         102 / 102 (100%)
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) website/app/Views/errors/html/error_exception.php (braces, unary_operator_spaces, not_operator_with_successor_space)
      ---------- begin diff ----------
--- /home/runner/work/website/website/app/Views/errors/html/error_exception.php
+++ /home/runner/work/website/website/app/Views/errors/html/error_exception.php
@@ -68,7 +68,7 @@
                                 } else {
                                     echo esc(clean_path($row['file']) . ' : ' . $row['line']);
                                 }
-                                ?>
+                    ?>
                             <?php else: ?>
                                 {PHP internal code}
                             <?php endif; ?>
@@ -83,14 +83,14 @@
                                         <table cellspacing="0">
 
                                         <?php
-                                        $params = null;
-                                        // Reflection by name is not available for closure function
-                                        if (substr($row['function'], -1) !== '}') {
-                                            $mirror = isset($row['class']) ? new \ReflectionMethod($row['class'], $row['function']) : new \ReflectionFunction($row['function']);
-                                            $params = $mirror->getParameters();
-                                        }
+                            $params = null;
+                                    // Reflection by name is not available for closure function
+                                    if (substr($row['function'], -1) !== '}') {
+                                        $mirror = isset($row['class']) ? new \ReflectionMethod($row['class'], $row['function']) : new \ReflectionFunction($row['function']);
+                                        $params = $mirror->getParameters();
+                                    }
 
-                                        foreach ($row['args'] as $key => $value) : ?>
+                                    foreach ($row['args'] as $key => $value) : ?>
                                             <tr>
                                                 <td><code><?= esc(isset($params[$key]) ? '$' . $params[$key]->name : "#{$key}") ?></code></td>
                                                 <td><pre><?= esc(print_r($value, true)) ?></pre></td>
@@ -308,8 +308,8 @@
             <!-- Response -->
             <?php
                 $response = \Config\Services::response();
-                $response->setStatusCode(http_response_code());
-            ?>
+$response->setStatusCode(http_response_code());
+?>
             <div class="content" id="response">
                 <table>
                     <tr>

      ----------- end diff -----------


Checked all files in 1.651 seconds, 20.000 MB memory used
Error: Process completed with exit code 8.
```
https://github.com/codeigniter4projects/website/runs/7797308582?check_suite_focus=true

**Review by Arhell — APPROVED** [review]

**Review by MGatner — APPROVED** [review]

**Comment by MGatner** [comment]
@kenjis I've been adding `exclude('Views/errors')` to all my project configs: https://github.com/duke-bluesmith/bluesmith/blob/develop/.php-cs-fixer.dist.php

**Comment by kenjis** [comment]
See https://www.codeigniter.com/download
The Download button's link is still https://api.github.com/repos/codeigniter4/CodeIgniter4/zipball/v4.2.6

When is the site update?

**Comment by MGatner** [comment]
The website is updated on push to `master`: **.github/workflows/deploy.yml**

We should get this released. I would like to be on desktop though, since we're still finalizing the deploy script reliability.

**Pull request merged**
