### PR TITLE
Deploy

### PR DESCRIPTION
**Pull request by kenjis**

### CODE REVIEW

**Review by lonnieezell — APPROVED** [review]

**Comment by kenjis** [comment]
@lonnieezell @MGatner The deployment failed.

```
Run yeshan333/rsync-deploy-action@main
/usr/bin/docker run --name ef7d8537ca839f6b6f4ec4a0cc35ff01bac863_1fd1a4 --label ef7d85 --workdir /github/workspace --rm -e "INPUT_SSH_LOGIN_USERNAME" -e "INPUT_REMOTE_SERVER_IP" -e "INPUT_SSH_PORT" -e "INPUT_SSH_PRIVATE_KEY" -e "INPUT_SOURCE_PATH" -e "INPUT_DESTINATION_PATH" -e "INPUT_SSH_ARGS" -e "INPUT_RSYNC_ARGS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/website/website":"/github/workspace" ef7d85:37ca839f6b6f4ec4a0cc35ff01bac863  "***" "***" "***" "***
" "./*" "/home/public_html/site/latest" "" ""
Saving private key......
Done
=========================================================================
Start time of synchronization  ->  Mon Sep  4 05:25:44 UTC 2023
Warning: Permanently added '***' (ED25519) to the list of known hosts.
***@***: Permission denied (publickey).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(231) [sender=3.2.7]
```
https://github.com/codeigniter4projects/website/actions/runs/6069476407/job/16463912346

**Comment by MGatner** [comment]
I will look on desktop later.

**Comment by kenjis** [comment]
See also https://github.com/codeigniter4/CodeIgniter4/issues/7464 if you have time.

**Comment by MGatner** [comment]
Ah, I see. Thank you. My SSH key no longer works either so I want to make sure there was no funny business before I regenerate everything from hosting.

**Comment by lonnieezell** [comment]
It looks like the SSH key had gotten removed at some point. I added it back to the server, installed a missing php-xml extension, and re-ran the action. It says it succeeded but the new website isn't live.

**Comment by kenjis** [comment]
It looks the deploy action did the job:
https://github.com/codeigniter4projects/website/actions/runs/6069476407/job/17164450784

**Comment by kenjis** [comment]
@lonnieezell It seems it restarted php7.4-fpm.

```
cd $RELEASE_DIR
sudo ln -nsf $RELEASE_DIR/$RELEASE "../current"
sudo service php7.4-fpm reload
```
https://github.com/codeigniter4projects/website/actions/runs/6069476407/job/17164450784

**Comment by lonnieezell** [comment]
New site is live! All it needed was to restart php. However, it seems we missed a limit on the "news" section where it pulls from the forums. I'll put together a PR for that now, and will include the fix for the deploy script as well.

**Comment by kenjis** [comment]
See #402

**Comment by kenjis** [comment]
I deployed #402 
See #403
Now the site works fine! 🎉🎉🎉

**Pull request merged**
