### PR TITLE
Dark mode fixes

### PR DESCRIPTION
**Pull request by kenjis**
Supersedes #390

See the diff https://github.com/codeigniter4projects/website/pull/395/files?w=1

### CODE REVIEW

**Comment by kenjis** [comment]
Before:
screenshot 2023-09-01 10 22 11

After:
screenshot 2023-09-01 10 22 17

**Review by lonnieezell — APPROVED** [review]

**Comment by lonnieezell** [comment]
Nice. Thanks!

**Comment by lonnieezell** [comment]
@kenjis Does this mean we're at a good spot to deploy the site again?

**Comment by kenjis** [comment]
@lonnieezell Yes. I think we can deploy now.

**Pull request merged**
